### ISSUE TITLE
Loading ... failed~

### ISSUE THREAD

**Issue by kklod** [kubauk/fava-review#10]
Got this..
![image](https://user-images.githubusercontent.com/50442661/209513852-01c61f98-ff8b-4ca9-89f9-640698432533.png)

**Comment by kubauk** [comment]
Hi, would be able to share the beancount file you used for this? Along with the version of Python, beancount and fava?

**Comment by vascosantos** [comment]
Hi, I'm also getting this error.
My setup is: 

- Windows 10 (on Ubuntu WSL) 
- Python 3.8.10 
- Beancount 2.3.5
- Fava 1.23.1

I am activating the extension like so:

`1970-01-01 custom "fava-extension" "fava_review" "{}"`

Here is what I get in the terminal window:

```
Exception on /vascos-personal-finances/extension/FavaReview/ [GET]
Traceback (most recent call last):
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vasco/.local/lib/python3.8/site-packages/fava/application.py", line 360, in extension_report
    content = Markup(render_template_string(template, extension=extension))
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/templating.py", line 159, in render_template_string
    return _render(app, template, context)
  File "/home/vasco/.local/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/vasco/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vasco/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 53, in top-level template code
  File "/home/vasco/.local/lib/python3.8/site-packages/fava_review/__init__.py", line 21, in get_income_statement_report
    return self.review.income_statement_by(g.interval)
  File "/home/vasco/.local/lib/python3.8/site-packages/fava_review/pivot_review.py", line 39, in income_statement_by
    return self.report_for(interval, ['Income', 'Expenses'])
  File "/home/vasco/.local/lib/python3.8/site-packages/fava_review/pivot_review.py", line 45, in report_for
    _, _, rows = self._ledger.query_shell.execute_query(self.review_query_for(interval, accounts))
TypeError: execute_query() missing 1 required positional argument: 'query'
```

**Comment by kubauk** [comment]
Thanks I can see what has happened now. There was a change in Fava that has made a method my plugin uses incompatible. https://github.com/beancount/fava/commit/6f4bcd5db8603a8baa4cdd190f22d62b0520db46 

If you drop your fava version down to 1.21 that should fix the issue for you.

It is not likely I will have time at the moment to fix the issue but if you are able to submit a pull request with a fix, I would happily look at it.

**Comment by kubauk** [comment]
@kklod can you please test against the latest version to see if that’s fixed your issue. This has not been published to PyPi yet so it would need to be a local install of the package.

**Comment by kubauk** [comment]
I've published the changes to version 0.9.1 on PyPi

**Comment by kklod** [comment]
> 
Thanks!  I'll try it later, kinda busy...

**Comment by kklod** [comment]
It works pretty well ! Thanks!
